### ISSUE TITLE
Error while setting up prismatik platform for light

### ISSUE THREAD

**Issue by YevhenPavliuchek** [zomfg/home-assistant-prismatik#12]
hassio last version

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/prismatik/light.py", line 65, in async_setup_platform
    await light.async_update()
  File "/config/custom_components/prismatik/light.py", line 300, in async_update
    profiles = await self._get_cmd(PrismatikAPI.CMD_GET_PROFILES)
  File "/config/custom_components/prismatik/light.py", line 222, in _get_cmd
    answer = await self._send(f"get{cmd}\n")
  File "/config/custom_components/prismatik/light.py", line 198, in _send
    answer = data.decode("ascii").strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 48: ordinal not in range(128)

**Comment by zomfg** [comment]
I assume your profile names are written in non-english letters, try renaming them with english alphabet for now (in Prismatik)

**Comment by YevhenPavliuchek** [comment]
indeed
there was one of old profiles in cyrillic
thx

**Comment by zomfg** [comment]
I pushed an update, you can re-try with cyrillic if you want
